name: Build and Deploy Lambda Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_NAME=legal-ocr-agent
          TAG=latest
          docker build -t $IMAGE_NAME:$TAG .

      - name: Tag Docker image for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=${{ secrets.AWS_REGION }}
          REPO_NAME=legal-ocr-agent
          IMAGE_TAG=latest
          ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

          docker tag legal-ocr-agent:$IMAGE_TAG $ECR_URI
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_URI

      - name: Deploy Lambda function with new image
        run: |
          aws lambda update-function-code \
            --function-name legal-ocr-agent \
            --image-uri $ECR_URI
