name: Build and Deploy Lambda Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1  
  IMAGE_NAME: legal-ocr-agent
  LAMBDA_FUNCTION_NAME: legal-ocr-agent

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Tag Docker image for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest

          docker tag ${{ env.IMAGE_NAME }}:latest $ECR_URI
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_URI

      - name: Deploy Lambda function with new image
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --image-uri $ECR_URI